"""Post update

Revision ID: 718edded4e74
Revises: 0ae7fa09d980
Create Date: 2024-05-27 15:35:46.498390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '718edded4e74'
down_revision = '0ae7fa09d980'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kp_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('kp_id')

    # ### end Alembic commands ###
